In [1]:
import pandas as pd
file_path='Global Superstore.txt'
df=pd.read_csv(file_path,sep="\t",encoding="utf-8")
df.head(3)

,Category,City,Country,Customer ID,Customer Name,Discount,Market,记录数,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32

In [13]:
df.describe()

,Discount,记录数,Profit,Quantity,Row ID,Sales,Shipping Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [4]:
df.columns

Index(['Category', 'City', 'Country', 'Customer ID', 'Customer Name',
       'Discount', 'Market', '记录数', 'Order Date', 'Order ID', 'Order Priority',
       'Product ID', 'Product Name', 'Profit', 'Quantity', 'Region', 'Row ID',
       'Sales', 'Segment', 'Ship Date', 'Ship Mode', 'Shipping Cost', 'State',
       'Sub-Category', 'Year', 'Market2', 'weeknum'],
      dtype='str')

In [4]:
early_column_position= df.columns.get_loc("Market")
early_column_position

6

In [5]:
unknown_column=df.iloc[:,early_column_position+1]

In [6]:
for i in unknown_column:
    if i != 1:
        print(i)

In [7]:
unknown_column.isna().sum()

np.int64(0)

In [8]:
df=df.rename(columns={unknown_column.name:"Record Count"})

In [9]:
df.head(3)

,Category,City,Country,Customer ID,Customer Name,Discount,Market,Record Count,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32

In [10]:
df.columns

Index(['Category', 'City', 'Country', 'Customer ID', 'Customer Name',
       'Discount', 'Market', 'Record Count', 'Order Date', 'Order ID',
       'Order Priority', 'Product ID', 'Product Name', 'Profit', 'Quantity',
       'Region', 'Row ID', 'Sales', 'Segment', 'Ship Date', 'Ship Mode',
       'Shipping Cost', 'State', 'Sub-Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [11]:
df["Profit"]<0

0        False
1        False
2        False
3        False
4        False
         ...
51285    False
51286    False
51287    False
51288    False
51289    False
Name: Profit, Length: 51290, dtype: bool

In [12]:
#find all orders that made a loss, display only Order ID Product Name Sales Profit Discount
loss=df.loc[df["Profit"]<0,["Order ID","Product Name","Sales","Profit","Discount"]]
loss.sort_values("Profit")

,Order ID,Product Name,Sales,Profit,Discount
47074,CA-2013-108196,Cubify CubeX 3D Printer Double Head Print,4500,-6599.9780,0.70
29353,TU-2013-9400,"Motorola Smart Phone, Cordless",3085,-4088.3760,0.60
47388,US-2014-168116,Cubify CubeX 3D Printer Triple Head Print,8000,-3839.9904,0.50
46422,CA-2011-169019,GBC DocuBind P400 Electric Binding System,2178,-3701.8928,0.80
47414,CA-2014-134845,Lexmark MX611dhe Monochrome Laser Printer,2550,-3399.9800,0.70
...,...,...,...,...,...
37814,ID-2014-60112,"Eaton Memo Slips, Premium",15,-0.0060,0.45
31110,US-2012-119438,"Safco Library with Doors, Pine",156,-0.0040,0.40
30050,IT-2013-5913315,"Office Star Swivel Stool, Adjustable",159,-0.0030,0.10
42250,ID-2012-28780,"Rubbermaid Frame, Black",562,-0.0021,0.27
30655,IN-2014-19274,"Rubbermaid Frame, Black",241,-0.0009,0.27

In [ ]:
#find which Sub-Category has the largest total loss, Group by Sub-Category, Calculate the total Profit for each sub-category
#Sort so the sub-category with the largest loss appears first

In [33]:
"""total_profit_subcategory=df.groupby("Sub-Category")["Profit"].sum().reset_index(name="total_profit")
#total_profit_subcategory
total_loss=df.groupby(("Sub-Category")[]
loss_possition=df.loc[df["Profit"]<0,["Sub-Category","Profit"]]
sorted_loss_possition=loss_possition.sort_values("Profit")
largest_loss=sorted_loss_possition.drop_duplicates(subset=["Sub-Category"],keep="first")
largest_loss.sort_values("Profit")"""

'total_profit_subcategory=df.groupby("Sub-Category")["Profit"].sum().reset_index(name="total_profit")\n#total_profit_subcategory\ntotal_loss=df.groupby(("Sub-Category")[]\nloss_possition=df.loc[df["Profit"]<0,["Sub-Category","Profit"]]\nsorted_loss_possition=loss_possition.sort_values("Profit")\nlargest_loss=sorted_loss_possition.drop_duplicates(subset=["Sub-Category"],keep="first")\nlargest_loss.sort_values("Profit")'

**find which Sub-Category has the largest total loss, Group by Sub-Category, Calculate the total Profit for each sub-category
**Sort so the sub-category with the largest loss appears first